name: Node continuous integration
on: push
jobs:
  build-node:
    name: Build node
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v2
      - run: npm install